version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: scheduler_postgres
    restart: always
    environment:
      POSTGRES_DB: schedulerdb
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: scheduler_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # Override the datasource URL to use the hostname 'postgres' (the service name)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/schedulerdb
      SPRING_DATASOURCE_USERNAME: scheduler
      SPRING_DATASOURCE_PASSWORD: scheduler

volumes:
  postgres_data:
